/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DISEÑO;

import javax.swing.ImageIcon;

/**
 *
 * @author leonardo
 */
public class recibo extends javax.swing.JFrame {

    /**
     * Creates new form recibo
     */
    public recibo() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/log.png")).getImage()); //imagen logo
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_monto = new javax.swing.JLabel();
        lbl_cuenta = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        bt_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RECIBO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 0, 220, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Monto:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Cuenta:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 140, 80, 30);

        lbl_monto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(lbl_monto);
        lbl_monto.setBounds(10, 90, 300, 30);

        lbl_cuenta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(lbl_cuenta);
        lbl_cuenta.setBounds(10, 180, 300, 30);

        jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel.setText("Fecha:");
        jPanel1.add(jLabel);
        jLabel.setBounds(10, 230, 60, 20);
        jPanel1.add(lbl_fecha);
        lbl_fecha.setBounds(10, 270, 290, 30);

        bt_salir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt_salir.setForeground(new java.awt.Color(51, 51, 51));
        bt_salir.setText("x");
        bt_salir.setToolTipText("Cerrar");
        bt_salir.setBorder(null);
        bt_salir.setBorderPainted(false);
        bt_salir.setContentAreaFilled(false);
        bt_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });
        jPanel1.add(bt_salir);
        bt_salir.setBounds(290, 0, 15, 20);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        this.dispose(); //accion salir
        
    }//GEN-LAST:event_bt_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recibo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_salir;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl_cuenta;
    public javax.swing.JLabel lbl_fecha;
    public javax.swing.JLabel lbl_monto;
    // End of variables declaration//GEN-END:variables
}
